name: Cypress Test
on: [push]
jobs: 
  Install-Run-Trello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2
             
      - name: Install App 
        run: npm install
        working-directory: ./app

      - name: start App 
        run: npm start
        working-directory: ./app

      - name: move to root directory
        working-directory: .
    
      - name: Checkout
        uses: actions/checkout@v4.1.2
        
      - name: Cypress.io
        uses: cypress-io/github-action@v6
      
