name: Cypress Test
on: [push]
jobs: 
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2
       - name: Cypress.io
        working-directory: ./
        uses: cypress-io/github-action@v6
      - name: Install App
        working-directory: ./app
        run: npm install
        start: npm start
     
          
    
