name: Cypress Test
on: [push]
jobs: 
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2
      - name: Change Directory
        run: cd ./app
      - name: Install Dependencies
        run: npm install
      - name: Start Application
        run: npm start
      - name: Run Cypress.io
        uses: cypress-io/github-action@v6.5.0

    
